#!/bin/bash

set \
  -o nounset \
  -o errexit
#  -o verbose
#  -o xtrace

TARGET_DIR=$(pwd)
cd "$(dirname "$0")"

INSTALLER_HOME=$(pwd)
JBOSS_CLI_SCRIPT="${INSTALLER_HOME}"/setup.cli
GRAPHQL_ZIP="${INSTALLER_HOME}"/smallrye-graphql.zip
CURRENT=$(readlink current)
VERSION=$(readlink "$CURRENT")

if [ $# -eq 0 ]; then
  TARGET="${TARGET_DIR}/wildfly-${VERSION}.Final"
else
  TARGET="${TARGET_DIR}/$1"
fi

if [ -d "$TARGET" ]; then
  echo Target directory \""${TARGET}"\" already exists. You can specify one as an argument. 1>&2
  exit 1
fi


################### unpack
TAR="${INSTALLER_HOME}"/wildfly-${VERSION}.Final.tar.gz

if [ ! -f "$TAR" ]; then
  echo Archive \""${TAR}"\" does not exist. 1>&2
  exit 2
fi

TEMP=$(mktemp -d)
cd "$TEMP"
echo Unpack "${TAR}" to "${TEMP}" 1>&2

tar -xzf "${TAR}"
# shellcheck disable=SC2046
# shellcheck disable=SC2005
# shellcheck disable=SC2012
FILE_COUNT=$(echo $(ls -A | wc -l))
if [ "${FILE_COUNT}" != 1 ]; then
  echo Expected exactly one root directory in "${TAR}" but found "${FILE_COUNT}": 1>&2
  ls -l 1>&2
  rm -r "${TEMP}"
  exit 3
fi
UNPACKED=$TEMP/$(ls)

mv "$UNPACKED" "$TARGET"
rmdir "$TEMP"
cd "${TARGET}"

################### modules
echo copy GraphQL modules 1>&2
unzip -q "${GRAPHQL_ZIP}"

################### configure
echo run config script "${JBOSS_CLI_SCRIPT}" 1>&2
./bin/jboss-cli.sh --file="${JBOSS_CLI_SCRIPT}"
